<a href="https://colab.research.google.com/github/Omkar-Potadar/Stat_With_Python/blob/main/One_Hot_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Nomial | One Hot Encoders

In [14]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [15]:
#create a sample dataframe with a categorical variable
df = pd.DataFrame({
    'color': ['red', 'blue','green','green', 'red','blue']
})

In [16]:
df

color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [17]:
##create on instanc of One hot  encoder
encoder=OneHotEncoder()

In [18]:
encoded=encoder.fit_transform(df[['color']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [20]:
import numpy as np
encoded_df=pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [21]:
new_df=pd.concat([df,encoded_df], axis = 1)
new_df

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

# Label And Ordinal Encoding

In [37]:

from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [38]:

df=pd.DataFrame({'color': ['red', 'blue','green','green', 'red','blue']})

In [48]:
# create an instance of labelencoder
encoder=LabelEncoder()

In [49]:
encoder.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

In [30]:
#ordinal Encoder

# Ordinal Encoder

In [33]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({'size': ['small','medium','large', 'medium', 'small','large']})

In [34]:
##create an instance of teh OrdinalEncoder class ad fit_transform
encoder=OrdinalEncoder(categories=[['small', 'medium','large']])

In [36]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])